### ISSUE TITLE
Ideas for CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by ikapelyukhin** [ilv/Text-Truncate#1]
Hello, everyone.

I was offered to contribute something to Text::Truncate as part of [CPAN Pull Request Challenge](http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html).

Here's the list of ideas I've compiled from talking to people in the challenge mail list and the maintainer:
1. Update its meta data;
2. Move it to Dist::Zilla (if the author is interested);
3. Benchmark to improve speed;
4. Check the Kwalitee metric (could be low due to lack to packaging mishaps);
5. Run Perl::Critic against it;
6. Use Devel::Cover to see what the test coverage is like. If less then 100%, then fix that :-)
7. Check how the module works with UTF-8 multi-byte characters, add test cases for the edge cases around strings with accented characters, etc., and then mention that in the doc;
8. The doc says: `use 5.00400;` but it also has `use warnings;`, which requires 5.006. Install Perl::MinimumVersion and check what the actual minimal version is;
9. Drop "vars" dependency and instead of `use vars` use: `our @EXPORT_OK = ...; our @EXPORT = ...; our $VERSION = '1.07';`
10. Replace: `require Exporter; @ISA = qw( Exporter );` with `use parent qw/Exporter/;`
11. There's a rogue comma at the end of the line:

`croak "continued symbol is longer than the cutoff length",
    if (length($marker) > $cutoff);`
12. Implement new features:
1. An option for truncate a text by words;
2. An option to truncate in complete sentences/paragraphs ([from RT](https://rt.cpan.org/Public/Bug/Display.html?id=51259)).

Links:
1. http://neilb.org/2014/11/29/pr-challenge-2015.html
2. http://neilb.org/2014/12/31/pr-ideas.html
3. http://neilb.org/2015/01/07/what-to-do.html

**Comment by ilv** [comment]
Hi.

Great. I see no problems in implementing ideas 1 to 11, except for 9 and 10. Could you be more specific on the reasons for doing those changes?

Most of the ideas 1 to 11 seem doable in a short period of time. Maybe after those points are finished we could discuss 12.

Thanks.

**Comment by somerandomlogin** [comment]
Items 9 and 10 are just style preferences, really. Although they might affect the minimum required version.

**Comment by ilv** [comment]
Hello. What do you think of implementing a new feature?

**Comment by somerandomlogin** [comment]
I think it's a great idea :-) I've been busy at work lately, I will once I have some free time (probably soon).

**Comment by ilv** [comment]
Awesome! Let's discuss it when you have some free time then (no hurries).
